directory: /data/music
library: /data/musiclibrary.db

paths:
  default: Albums/%title{$albumartist}/$album%aunique{}/$track $title
  singleton: Singles/%title{$artist}/$title
  comp: Compilations/$album%aunique{}/$track $title

plugins:
  - websearch
  - ytimport

websearch:
  host: 127.0.0.1
  port: 5000

ytimport:
  directory: /data/ytimport
