openapi: "3.0.1"
info:
  title: Song search and playlist generator API
  description: Song search and playlist generator API
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: Max Goltzsche
    url: https://github.com/mgoltzsche/beets-websearch
    email: max.goltzsche@gmail.com

servers:
  - url: /

tags:
  - name: websearch

paths:
  /attributes:
    get:
      operationId: attributes
      summary: Lists attribute definitions
      description: |
        Lists attributes that can be used as search criteria.
        (The frontend could generate a search form based on this data.)
      tags:
        - websearch
      responses:
        '200':
          description: Attribute definitions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttributeDefinitionList'
  /attributes/{attribute}/info:
    get:
      operationId: getAttributeInfo
      summary: Get the attribute value range
      description: |
        Provides the range of values for a given attribute definition and search query.
      tags:
        - websearch
      parameters:
        - name: attribute
          in: path
          description: Attribute name
          required: true
          schema:
            type: string
        - name: query
          in: query
          explode: true
          description: |
            Search query to support drill-down search.
            Can be specified multiple times as a union.
            It accepts a JSON-encoded query object.
          required: false
          schema:
            type: array
            items:
              type: string
            example:
              - '{"genre": {"eq": "Dubstep"}, "bpm": {"lt": "90"}}'
      responses:
        '200':
          description: Supported attribute value range
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttributeInfo'
  /tracks:
    get:
      operationId: listTracks
      summary: List/search tracks
      description: List and search tracks.
      tags:
        - websearch
      parameters:
        - name: query
          in: query
          explode: true
          description: |
            Search query.
            Can be specified multiple times as a union.
            It accepts a JSON-encoded query object.
          required: false
          schema:
            type: array
            items:
              type: string
            example:
              - '{"genre": {"eq": "Dubstep"}, "bpm": {"lt": "90"}}'
      responses:
        '200':
          description: Search result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrackList'
  /playlists:
    get:
      operationId: listPlaylists
      summary: List playlists
      description: List all playlists.
      tags:
        - websearch
      responses:
        '200':
          description: List of playlists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaylistList'
    post:
      operationId: createPlaylist
      summary: Create playlist
      description: Create a new playlist based on the given set of song queries.
      tags:
        - websearch
      requestBody:
        description: Playlist that should be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Playlist'
      responses:
        '201':
          description: Playlist created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Playlist'
    put:
      operationId: updatePlaylist
      summary: Update playlist
      description: Update an existing playlist.
      tags:
        - websearch
      requestBody:
        description: Playlist that should be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Playlist'
      responses:
        '201':
          description: Playlist updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Playlist'
  /playlists/{playlist}:
    delete:
      operationId: deletePlaylist
      summary: Delete playlist
      description: Delete a playlist.
      tags:
        - websearch
      parameters:
        - name: playlist
          in: path
          description: Playlist name
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Playlist created

components:
  schemas:
    TrackList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Track'
      required:
        - items
    Track:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
      additionalProperties:
        type: string
      required:
        - id
        - title
      example:
        id: "123"
        artist: Dengue Dengue Dengue
        title: Serpiente Dorada
        bpm: 70
    AttributeDefinitionList:
      type: object
      properties:
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/AttributeDefinition'
        types:
          type: array
          items:
            $ref: '#/components/schemas/AttributeTypeDefinition'
      required:
        - attributes
        - types
      example:
        attributes:
          - name: bpm
            type: int
            title: BPM
        types:
          - name: int
            operators:
              - gt
              - lt
              - eq
          - name: string
            operators:
              - eq
              - contains
              - regex
          - name: date
            operators:
              - eq
              - gt
              - lt
    AttributeTypeDefinition:
      type: object
      properties:
        name:
          type: string
        operators:
          type: array
          items:
            type: string
      required:
        - name
        - operators
    AttributeDefinition:
      type: object
      properties:
        name:
          type: string
        title:
          type: string
        type:
          type: string
          enum:
            - string
            - int
            - float
            - bool
            - date
      required:
        - name
        - title
        - type
    AttributeInfo:
      type: object
      description: Supported value ranges
      properties:
        name:
          type: string
        values:
          type: array
          items:
            type: string
        minValue:
          type: number
        maxValue:
          type: number
      required:
        - name
      example:
        name: bpm
        minValue: 50
        maxValue: 123
    PlaylistList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Playlist'
      required:
        - items
    Playlist:
      type: object
      properties:
        name:
          type: string
        created:
          type: string
          example: "2024-07-14T16:16:16Z"
        query:
          $ref: '#/components/schemas/Query'
      required:
        - name
      example:
        name: Slow/dark Dubstep
        created: "2024-07-14T16:16:16Z"
        query:
          - {"genre": {"eq": "Dubstep"}, "bpm": {"lt": "90"}}
    Query:
      type: array
      items:
        type: object
        additionalProperties:
          $ref: '#/components/schemas/Operation'
      example:
        - {"genre": {"eq": "Dubstep"}, "bpm": {"lt": "90"}}
        - {"genre": {"eq": "Grime"}, "bpm": {"lt": "105"}}
    Operation:
      type: object
      properties:
        lt:
          type: string
        gt:
          type: string
        eq:
          type: string
        contains:
          type: string
        regex:
          type: string
