openapi: "3.0.1"
info:
  title: Media Server
  description: M3U playlist and audio stream server.
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: Max Goltzsche
    url: https://github.com/mgoltzsche/beets-websearch

servers:
  - url: /

tags:
  - name: media

paths:
  /playlists.m3u:
    get:
      operationId: getM3UIndex
      summary: Get index EXTM3U playlist that lists all playlists
      description: Get the index playlist that contains URLs pointing to the actual playlists.
      tags:
        - media
      parameters:
        - name: uri-format
          in: query
          description: |
            A playlist item URI template.
            Dollar-prefixed item/song field names can be used as placeholders, e.g. `beets:library:track;$id` or `subidy:song:3$id`.
            `$url` is a built-in placeholder and the default value.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Index playlist in EXTM3U format
          content:
            audio/mpegurl:
              schema:
                type: string
                example: |
                  #EXTM3U
                  #EXTINF:0,Playlist 1
                  http://localhost:5000/playlists/playlist1.m3u
                  #EXTINF:0,Playlist 2
                  http://localhost:5000/playlists/playlist2.m3u
  /playlists/{playlistId}.m3u:
    get:
      operationId: getM3UPlaylist
      summary: Get playlist in EXTM3U format
      description: Get the tracks contained within a playlist in the EXTM3U format.
      tags:
        - media
      parameters:
        - name: uri-format
          in: query
          description: |
            A playlist item URI template.
            Dollar-prefixed item/song field names can be used as placeholders, e.g. `beets:library:track;$id` or `subidy:song:3$id`.
            `$url` is a built-in placeholder and the default value.
          required: false
          schema:
            type: string
      parameters:
        - name: playlistId
          in: path
          description: Playlist ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: EXTM3U playlist
          content:
            audio/mpegurl:
              schema:
                type: string
                example: |
                  #EXTM3U
                  #EXTINF:0,Track 1
                  http://localhost:5000/tracks/1/audio
                  #EXTINF:0,Track 2
                  http://localhost:5000/tracks/2/audio
  /tracks/{id}/audio:
    get:
      operationId: getAudioData
      summary: Get audio data for the given track ID
      description: Get/stream audio data for the given track ID.
      tags:
        - media
      parameters:
        - name: id
          in: path
          description: Beets item ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Audio data
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
